### ISSUE TITLE
Maps: "Kartenstrukturen > Mehrere bearbeiten" manche Felder werden nicht angezeigt

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#11]
Wenn ich unter Kartenstrukturen "Mehrere bearbeiten" anwähle und dann aus den vorhandenen Feldern das Feld "Alle Lokationen anzeigen [show_locations]" anwähle, werden danach etliche Felder nicht angezeigt.

Folgende Felder sind betroffen:

Breite der Karte [width]
Höhe der Karte [height]
Abstand der Karte [margin]
calc_extent [calc_extent]
Alle Lokationen anzeigen [show_locations]
Mindestabstand der Lokationen zum Kartenrand in Pixeln [min_gap]
Icon für den Reiter [awesomeicon]
Geo X-Koordinate [center_geox]
Geo Y-Koordinate [center_geoy]
Zoom-Level [zoom]
Aktuelle Position ermitteln [geolocation]
Aktuelle Position - Zoomlevel [geolocation_zoom]
Kartenausschnitt einschränken [restrict_area]
Geo X-Koordinate links [restr_bottomleft_geox]
Geo Y-Koordinate unten [restr_bottomleft_geoy]
Geo X-Koordinate rechts [restr_topright_geox]
Geo Y-Koordinate oben [restr_topright_geoy]
Hierarchisch untergeordnete Kartenstrukturelemente berücksichtigen [include_sublocations]
Art der Popup-Generierung [popupType]
Popup Template [popupTemplate]
Popup Information durch Forenbeitrag erweitern [popup_extend]
Quelltabelle [tab_source]
Lokationen asynchron nachladen [async_content]
Eintrag aus Elterntabelle (optional) [tab_pid]
Zweiter Eintrag aus Elterntabelle (optional) [tab_pid1]
Anzeige von Labels [tab_labeldisplay]
Anzeige von Tooltips [tab_tooltipdisplay]
Direktlink generieren [tab_directlink]
Popup-Links immer in neuem Fenster öffnen [tab_force_target_blank]
WHERE-Bedingungen [tab_whereclause]
Join-Bedingungen [tabJoinclause]
Sortierung [tab_orderby]
Nur aktuellen Eintrag anzeigen [tab_filter_alias]
Datei [data_file]
Verzeichnis [data_folder]
Geojson aufteilen [split_geojson]
Attribute des Geojson [geojson_attributes]
Zoombutton für GeoJson [geojson_zoom]
URL [data_url]
Daten [data_content]
Koordinatensystem [data_projection]
Flächen und Wege in Knoten umwandeln [data_forcenodes]
Zusätzliche Geometrien anzeigen [data_additionalgeometries]
Diskussionsforen [forums]
Weiterleitungsseite mit Forum [forum_jumpto]
Forum - in andere Ebene verschieben [forum_reassign_layer]
Anfrage an Overpass API (XML-Format) [ovp_request]
Anfrage an Overpass API auf den angezeigten Kartenbereich (BBOX) beschränken. [ovp_bbox_limited]
Kartenstrukturelement [link_id]
Berechtigte Gruppen [permitted_groups]
Spezialprofil aktivieren [use_specialprofile]
Spezialprofil [specialprofile]
Spezialprofil mobil [specialprofile_mobile]
Betroffene Gruppen [specialprofile_groups]
Lokationen clustern [cluster_locations]
Cluster-Distanz [cluster_distance]
Füllfarbe [cluster_fillcolor]
Schriftfarbe [cluster_fontcolor]
Minimale Zoomstufe (Spinne) [cluster_zoom]
Popup beim Clustern [cluster_popup]
Lokationsstil bei Hover-Effekt [hover_style]

Die restlichen Felder werden angezeigt. 

Jörn

**Comment by coastforge-mei** [comment]
Hallo Jörn,

wir machen heute die 5.1 und da habe ich das noch mal genauer angeschaut. Es werden nur Felder angezeigt, wenn diese auch im Dialog aktiv wären. In der Kartenstruktur werden ja sehr viele Felder ein- und ausgeblendet. D.h., wenn es das Feld im Element aktuell nicht gibt, erscheint eine leere Zeile. Anders verhält es sich, wenn ein Feld mit dargestellt wird, welches immer vorhanden ist. Bspw. der Name, dann tauch die weiße Zeile nicht auf. Bin mir nicht sicher, ob wir da überhaupt etwas dran ändern können, werde das aber für den nächsten DCA-Umbau im Hinterkopf behalten.

Beste Grüße
Matthias

**Comment by joehi** [comment]
Moin Matthias,

aufgefallen ist mir der Effekt, als ich bei mehreren Einträgen vorhandene Felder editieren wollte und mir diese nicht angezeigt wurden. Bevor ich den Eintrag hier gemacht hatte, habe ich dann alle weiteren Felder auch durchprobiert und gesucht, welche Felder noch nicht angezeigt wurden.

Es sind also auch Felder betroffen, die im Dialog aktiv wären und dann auch bei "mehrere bearbeiten" angezeigt werden sollten.

Jörn

**Comment by coastforge-mei** [comment]
Hallo Jörn,

wir haben versucht den Fehler nachzustellen. Leider ohne Erfolg. Wir schliessen das Issue erst einmal ab. Falls der Fehler mit der nächsten Version (heute oder morgen) immer noch auftritt, mach bitte ein kleines Beispiel. Also ein Feld bei dem das "Mehrere Bearbeiten" nicht funktioniert.

Danke
Matthias
