### ISSUE TITLE
Insert-Tags im GeoJSON-Format werden nicht ersetzt

### ISSUE THREAD

**Issue by christianbarkowsky** [Kuestenschmiede/MapsBundle#12]
Werden Kartenelements im _GeoJSON-Format_ bereitgestellt, so werden beinhaltete Insert-Tags nicht mehr ersetzt.

`{"type": "FeatureCollection",
"features": [
{"type": "Feature",
	"properties": {
		"website": "{{article_url::176}}",
		...
`

**Comment by coastforge-mei** [comment]
Fixed in 3f6810c99400531ed4fdc871f4f1e1c7b4a6e7e4.
