### ISSUE TITLE
Karten werden nicht angezeigt, weder im Frontend noch im Backend

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#14]
Nach einem Update von con4gis-Maps von 5.1.6 auf 6.0.4 werden sowohl im Frontend als auch im Backend (Editor um Geo-Koordinaten festzulegen) keine Karten mehr angezeigt.
Auch das neue Anlegen einer Karte unter v6.0.4 nach dem Beispiel der Anreisekarte hat nicht funktioniert.

Das Nachinstallieren des Paketes con4gis-Editor brachte ebenfalls keine Änderung.

**Comment by coastforge-mei** [comment]
Mit dem Major Release hat sich einiges verändert. Bei mir lokal habe ich eine aktuelle 4.7 mit Maps und Editor. Das Anlegen einer Karte funktioniert problemlos. Bzgl. des neuen Editors veröffentlichen wir in Kürze eine Schnellanleitung unter docs.con4gis.org. Ggf. gibt es bei Dir mit der alten Editor-Konfiguration Probleme? Bitte überprüfe mit der neuen Doku dann noch mal die Einstellungen und melde Dich wieder falls es weiterhin Probleme gibt. Bitte prüfe in der Browserkonsole auch, ob jQuery geladen wird.

**Comment by joehi** [comment]
jQuery wird geladen, soweit ich das sehen kann. Aber ich erhalte in der Browserkonsole einen Fehler:
c4g-maps.js: can not get element by id mapData.mapDiv

Das stammt aus folgendem Programmteil ziemlich am Ende der Datei:
```
this.proxy.hook_layer_visibility.push(n)),
(s = document.getElementById(r.mapDiv)) && s.style) {
...
} else
                    console.warn("can not get element by id mapData.mapDiv")

```

**Comment by joehi** [comment]
Nach dem heutigen Update auf con4gis-core v3.2.6 sowie con4gis-maps v6.0.5 werden die Karten sowohl im Frontend auf der Webseite als auch im Backend im Geo-Editor wieder angezeigt.

Im Backend beim Geo-Editor wird die Suchmaske jedoch nicht (mehr) angezeigt, in der Browserconsole wird eine Fehlermeldung ausgegeben:
jquery.min.js:2 GET https://example.com/con4gis/layerService/0 404 (Not Found)

c4g-layer-controller.js:51: An error occured while trying to load the layers...

Wenn ich die 0 am Ende der obigen URL durch eine 1, 2 oder 3 ersetze, erhalte ich keinen Error 404 sondern einen 200 OK samt zugehörigen Daten.

**Comment by coastforge-mei** [comment]
Dieses Issue ist meines Wissens mit der v6.0.7 erledigt.

**Comment by joehi** [comment]
Ja, seit v6.0.5 funktioniert es wieder und die Karten werden angezeigt. Auch die Suchmaske wird angezeigt.

Nur das Problem mit dem Fehler 404 besteht weiterhin im Geo-Editor im Backend.
