### ISSUE TITLE
"Nur aktuellen Eintrag anzeigen" funktioniert nicht mehr

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#15]
Nach einem Update von con4gis-Maps von 5.1.6 auf 6.0.7 erscheint auf der Karte bei Auswahl "Nur aktuellen Eintrag anzeigen" im Frontend kein Eintrag mehr.
Somit ist es aktuell nicht mehr möglich, (nur) den Ort des aktuellen Termins in der Karte anzuzeigen.
Die Anzeige aller Orte aller Termine in einer (anderen) Karte funktioniert.

**Comment by coastforge-mei** [comment]
Danke für die Meldung. Wir prüfen das und beheben den Fehler schnellstmöglich.

**Comment by joehi** [comment]
Wenn ich zusätzlich im Feld "**WHERE-Bedingungen**"
`id = id`
eintrage, funktioniert es (erstmal) wieder. Bisher war dieses Feld leer.
Der Haken bei "Nur aktuellen Eintrag anzeigen" muß weiterhin gesetzt sein.

**Comment by coastforge-fsc** [comment]
Das Problem wird in der kommenden Version diese Woche behoben. Es wurde nicht abgefangen, wenn es vorher keine einschränkende WHERE-Bedingung gab. Mit deiner Bedingung, die immer true ergibt, hast du das Problem erstmal gelöst.

**Comment by joehi** [comment]
Hatte mich schon gewundert, warum die Bedingung geholfen hat. Hatte erst mit festen Werten  (id=123) experimentiert und bin dabei auch über obige "true"-Bedingung gestolpert.

**Comment by coastforge-mei** [comment]
Behoben mit v6.0.8.
