### ISSUE TITLE
Das Popup-Fenster wird immer mittig auf der Karte platziert anstelle direkt über dem jeweiligen Punkt

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#23]
Bisher erschien das Popup-Fenster direkt über dem jeweiligen Eintrag auf der Karte beim Anklicken. Jetzt erscheinen die Popup-Fenster fälschlicherweise immer mittig auf der angezeigten Karte.

Dieser Fehler trat bis einschließlich con4gis/maps (v6.0.9) nicht auf.

**Comment by coastforge-mei** [comment]
Moin Jörn,

im Profil gibt es drei Varianten für die Ausgabe des Popups. Ggf. ist der Default-Wert bei Dir nicht gesetzt (klassisches Handling). Hast Du ein Update von einer Version < 6 gemacht? Ich werde das in den aktuellen Sourcen auch noch prüfen.

Beste Grüße
Matthias

**Comment by joehi** [comment]
Moin Matthias,

ja, als ich con4gis/maps erstmals installiert habe, war es noch in der der Version 5.x.

Deine Vermutung trifft zu, es war kein Default-Wert gesetzt. Nachdem ich "Classic handling (popup points to element position)" ausgewählt habe, funktioniert es wieder wie gewünscht.

Vielen Dank.

Viele Grüße,
Jörn
