### ISSUE TITLE
Insert Tags werden nicht mehr ersetzt

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#26]
In Version con4gis/maps v6.2.8 sowie v6.2.9 werden Insert Tags nicht mehr ersetzt sondern ungefiltert durchgereicht. Dadurch funktionieren interne URLs und eingebundene lokale Bilder im Popup nicht mehr.

In con4gis/maps v6.2.7 wurden Insert Tags noch erfolgreich ersetzt.
Lediglich die sprachabhängigen Insert Tags funktionieren auch hier noch nicht korrekt, aber das ist ein älteres, weiterhin bestehendes Problem.

**Comment by coastforge-cro** [comment]
Das Problem ist in der 6.2.10 behoben. Auch die sprachabhängigen Tags laufen im Popup jetzt.

**Comment by joehi** [comment]
Vielen Dank für den Fix, die internen URLs funktionieren jetzt in den Popups wieder.

Die sprachabhängigen Insert Tags funktionieren bei mir in den Popups aber weiterhin nicht.
"{{page::language}}" liefert weiterhin einen leeren String und nicht die aktuell verwendete Sprache.
"Deutsch? {{iflng::de}}Ja{{iflng}}{{ifnlng::de}}Nein{{ifnlng}}" liefert immer "Nein" sowie
"English? {{iflng::en}}Yes{{iflng}}{{ifnlng::en}}No{{ifnlng}}" liefert immer "No", egal ob ich die Seite in Deutsch oder Englisch aufrufe.
Binde ich das gleiche auf einer normalen Seite in ein Textelement ein, funktioniert es wie erwartet.

**Comment by coastforge-cro** [comment]
Danke für deine Rückmeldung, wir gehen das noch einmal an.

**Comment by coastforge-cro** [comment]
Das Problem ist in der aktuellsten Version gefixt, es funktionieren nun wieder beide Inserttags.

**Comment by joehi** [comment]
Habe gerade ein Update auf Version v6.2.12 gemacht. Bei meiner Installation hat sich leider keine Verbesserung ergeben. Es gilt weiterhin mein obiger Text bezüglich der sprachabhängigen Insert Tags.
Bei meinen Installationen haben die sprachabhängigen Insert Tags auch vorher noch nie funktioniert, soweit ich das beobachtet habe. Ich nutze Contao Version 4.8.4.

**Comment by coastforge-cro** [comment]
Wir haben nochmal Anpassungen gemacht. Die 6.2.13 sollte das Problem nun hoffentlich auch in deiner Installation beheben.

**Comment by joehi** [comment]
Ja, nach dem Update auf die 6.2.13 funktionieren jetzt auch die sprachabhängigen Insert Tags in meiner Installation.
Vielen Dank.

**Comment by joehi** [comment]
Komplett funktionsfähig ist es doch noch nicht, wie ich gerade feststellen mußte.

Sprachabhängige Insert Tags mit reinem Text funktionieren:
`Text: {{iflng::de}}Deutsch{{iflng}}{{ifnlng::de}}English{{ifnlng}}`

Wenn jedoch ein weiteres Insert Tag wie z.B. eine URL verschachtelt eingefügt wird, funktioniert es noch nicht:
`URL: {{iflng::de}}<a title="Deutsch" href="{{link_url::2}}">Deutsch</a>{{iflng}}{{ifnlng::de}}<a title="English" href="{{link_url::4}}">English</a>{{ifnlng}}`

**Comment by coastforge-cro** [comment]
In der 6.2.15 sollten nun auch die verschachtelten InsertTags funktionieren.
