### ISSUE TITLE
Events werden nicht mehr in der Karte angezeigt

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#28]
In der Version v6.2.12 werden die Events nicht mehr in der Karte angezeigt, es erscheint nur noch eine leere Karte.
In der Version v6.2.10 wurden die Events noch wie gewohnt in der Karte angezeigt.

**Comment by coastforge-cro** [comment]
Dort hat sich leider ein Fehler eingeschlichen. Die Events funktionieren in der 6.2.13 wieder.

**Comment by joehi** [comment]
Vielen Dank für den schnellen Fix.
