### ISSUE TITLE
Update auf Version v4.2.0 - Marker wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by planepix** [Kuestenschmiede/MapsBundle#3]
Ahoi an die Küstenschmiede.

Ich habe via Contao Manager heute die 4.4.8 Installation aktualisiert.
Dabei wurde con4gis/maps auf Version v4.2.0 aktualisiert; ebenso con4gis/core.

Nach der Aktualisierung wird nun der Marker nicht mehr angezeigt.
Alle Marker und Einstellung noch mal abgespeichert.

Testweise einen neuen Marker erstellt --> wird auch nicht angezeigt.

Die Konsole im Browser sagt:
```
An error occured while trying to load the layers...
(anonymous) @ c4g-maps-proxy.js:1632
```

Was kann ich noch beisteuern an Informationen?

Contao 4.4.8
PHP 7.1
Hoster allinkl.

Danke und Grüße nach Jever
Thomas

**Comment by coastforge-mei** [comment]
Moin Thomas,

wir hatten einige der Backend-Felder "InsertTag-tauglich" gemacht, dass hat bei manchen Kartenstrukturelementen (z.B. aus anderer Tabelle) abhängig vom Inhalt einen Fehler geschmissen, der jetzt mit der 4.2.1 behoben sein sollte. Bitte mal testen.

Beste Grüße
Matthias

**Comment by planepix** [comment]
Moin Matthias,
besten Dank für die Erklärung.

Nach dem Update auf 4.2.1 wird der Marker wieder angezeigt. Danke für den Fix.

Beste Grüße
Thomas
