### ISSUE TITLE
Bei Location Style fehlen die Bezeichnungen für "Stroke opacity" sowie "Fill opacity"

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#32]
Beim Update von Version 6 zu Version 7 scheinen beim Location Style die Bezeichnungen für die Felder "Stroke opacity" sowie "Fill opacity" verloren gegangen zu sein. Auch wurden die dort eingetragenen Werte beim Update nicht übernommen sondern die Felder waren leer.

**Comment by coastforge-mei** [comment]
Wir haben für das Major-Release den Feldtyp verändert. Es ist leider so, dass die Werte verloren gehen. Die Feldbezeichnung sind nicht verloren gegangen. Genau wie an anderer Stelle in Contao befinden sich jetzt beide Eingabefelder in einem "Contao Feld". Die Überschrift gilt also für beide Eingaben (Farbe und Deckkraft).
