### ISSUE TITLE
angezeigte Version im Dashboard wird nicht aktualisiert und stimmt nicht mit der aktuellen Version überein

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#33]
Laut Contao-Manager ist die con4gis-Maps Version v7.0.16 installiert, im Backend im con4gis Dashboard wird jedoch bei maps angezeigt, dass 7.0.15 installiert ist und die neueste Version v7.0.15 ist. Das Update auf v7.0.16 erfolgte kurz nach Veröffentlichung der Version, liegt also schon ein paar Tage zurück.

Bei einer heute aktualisierten Version wird im sowohl vor als auch nach dem Update angezeigt, dass Version 7.0.15 installiert sei und Version v7.0.16 verfügbar sei, bei con4gis-Core ist es ebenso, dort steht 4.0.11 und dass v4.0.12 verfügbar sei.

Anscheinend werden die Versionen im Dashboard nicht aktualisiert.

**Comment by joehi** [comment]
Heute werden jetzt die korrekten Versionen in der ersten oben genannten Installation, die bereits vor einigen Tagen das Update bekommen hatte, angezeigt. Bei der Installation, wo das Update erst gestern eingespielt wurde, werden weiterhin im Dashboard die falschen Versionsangaben mit Stand von vor dem Update angezeigt.
Wird die Seite Dashboard im Backend evtl. zu lange gecached?

**Comment by coastforge-mei** [comment]
Wir möchten die Versionen nicht jedes Mal laden, da das immer etwas Zeit in Anspruch nimmt. Deshalb haben wir den "Versionen aktualisieren" Button eingeführt. Ich werde aber noch mal schauen, ob ich das automatische Aktualisieren nach einem Update besser triggern kann.

**Comment by joehi** [comment]
Danke für den Hinweis. Den Button hatte ich bisher erfolgreich übersehen.
