### ISSUE TITLE
Basiskarte Openstreetmap Deutschland Stil wird nicht angezeigt (Version 7.0.16)

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#34]
In der Version 7.0.16 werden keine Karten von OpenStreepMap im OSM Style "Deutschland Stil" angezeigt, die Karte bleibt leer (weiß). Wähle ich "Mapnik" aus, wird eine Karte angezeigt.
In der Version 6.3.1 funktioniert es hingegen, dort kann man zwischen beiden Kartenstilen wechseln und die Karten werden entsprechend angezeigt.

**Comment by coastforge-mei** [comment]
Wir werden beide Versionen vergleichen und den Zugriff wenn möglich korrigieren.

**Comment by joehi** [comment]
In der Console gibt es Fehlermeldungen der folgenden Art:
`Access to image at 'https://a.tile.openstreetmap.de/tiles/osmde/6/33/21.png' from origin 'https://example.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
sowie
`GET https://a.tile.openstreetmap.de/tiles/osmde/6/33/21.png net::ERR_FAILED`

**Comment by coastforge-mei** [comment]
Behoben in 7.0.17.

**Comment by joehi** [comment]
Das kann ich leider noch nicht bestätigen. Auch nach dem Update auf 7.0.17 erhalte ich weiterhin die Fehlermeldungen und es wird keine Karte angezeigt.

**Comment by joehi** [comment]
In der Version 7.0.18 funktioniert es jetzt. Vielen Dank.
