### ISSUE TITLE
Fehlerhafte Auflösung von URLs bei mehrsprachiger Installation

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#35]
Im Popup eingetragene URLs zur Hauptsprache bei mehrsprachigen Seiten werden falsch aufgelöst. Dieser Fehler tritt in der Version maps 7.0.18 als auch maps 6.3.1 auf.

Bei einer mehrsprachigen Installation habe ich im Popup URLs zu  je einer Seite in jeder der Sprachen. In der Hauptsprache sind alle URLs korrekt. Bei den anderen Sprachen wird die URL zur Hauptsprache (Fallback) falsch gebildet, es wird fälschlicherweise die aktuell ausgewählte Sprache anstelle der Hauptsprache in der URL eingesetzt.

Korrekte URLs (bei Hauptsprache DE):
```
example.com/de/seite1.html
example.com/en/page2.html
```
Fehlerhafte URLs (bei weiterer Sprache EN):
```
example.com/en/seite1.html
example.com/en/page2.html
```
Hier steht fälschlicherweise "en" in der URL example.com/**en**/seite1.html obwohl es korrekt "de" und damit die URL example.com/**de**/seite1.html sein müsste.

**Comment by coastforge-cro** [comment]
Hallo joehi, 
ich nehme an, du nutzt Inserttags? Welche Tags verwendest du genau?
Und was verwendest du, um die Sprachen zu wechseln, ist dafür noch eine weitere Extension/Bundle installiert?

**Comment by joehi** [comment]
Ich habe das ganz bequem mit dem eingebauten Editor gemacht. Wenn ich im Editor auf die Source code Ansicht umschalte, sieht man die Interttags:
```
<a href="{{link_url::11}}">Deutsche Seite</a>
<a href="{{link_url::22}}">English page</a>
```
Ich verwende den Sprachenwechlser `terminal42/contao-changelanguage`.

Bei den Karten habe ich mir bisher damit beholfen, jeweils eine URLs zur Detailseite in beiden Sprachen zu setzen. Wenn maps mehrsprachig wird, könnte ich das dann etwas aufräumen, so dass nur noch die URL zur Detailseite der aktuell verwendeten Sprache angezeigt wird.

**Comment by coastforge-cro** [comment]
Deine Inserttags fügen ja immer die URL einer Seite mit fester ID ein. Das sollte ja also eigentlich gar nicht von der Sprache abhängen?
Scheinbar geht in Verbindung mit dem contao-changelanguage dort etwas schief, das schauen wir uns noch genauer an.

**Comment by coastforge-cro** [comment]
In der nächsten Version kommt ein Bugfix hierfür mit. Wir versuchen, die Version noch diese Woche zu veröffentlichen.

**Comment by joehi** [comment]
Super, vielen Dank.

**Comment by coastforge-mei** [comment]
Behoben mit v7.0.19.
