### ISSUE TITLE
Steuerelemente zum Zoomen werden bei zwei Karten falsch positioniert. (v7.0.19)

### ISSUE THREAD

**Issue by Webstylerin** [Kuestenschmiede/MapsBundle#36]
Hallo,

ich nutze Contao 4.9.2 mit con4gis-Maps v7.0.19 und habe 2 Karten auf einer Seite. Allerdings wird das Steuerelement für den Zoom für beide Karten auf der ersten Karte angezeigt (sowohl sichtbar als auch im Code). Das zweite Elemente steuert aber die zweite Karte.

Ich gehe davon aus, das ist nicht so gewollt? :) Falls doch bzw. es eine Einstellung dafür gibt, die ich übersehen habe, bitte ich um einen dezenten Zaunpfahl.

LG
Nicole

![maps](https://user-images.githubusercontent.com/3033160/80910928-3299a500-8d33-11ea-84e6-0d01cb86a670.png)

**Comment by coastforge-mei** [comment]
Hallo Nicole,

dass ist auf keinen Fall gewollt :) Mehrere Karten auf einer Seite sind selten. Ggf. haben wir hier ein grundsätzliches Problem. Wir werden das nachstellen und versuchen eine allgemeine Lösung zu finden.

Beste Grüße
Matthias

**Comment by coastforge-fsc** [comment]
Hallo Nicole,
ich konnte das Problem jetzt so nicht nachstellen. Wie sind die Karten denn eingebunden?

**Comment by Webstylerin** [comment]
Hi,

also, ich habe über das Dashborad eine Basiskarte, einen Lokationsstil, ein Kartenlayout und ein Kartenprofil angelegt. Hauptsächlich mit Standard-Parametern. Dann habe ich zwei Kartenstrukturen angelegt, für die zwei verschiedene Adressen. Nachdem in der neuen Version keine Lokation direkt über die Kartenstruktur anlegen konnte, habe ich die angelegten Strukturen kopiert, in den Kopien "Einzelne Geo-Koordinate" eingestellt und diese unter die passende Struktur mit dem Elementyp "Karte" gelegt.

Eingebunden sind die Karten direkt in einem Artikel mit dem Elementtyp Karte.

Ich habe noch einen etwas früheren Entwicklungsstand der Seite auf meinem Server, der den Fehler enthält. Dazu könnte ich euch Zugang geben.

VG
Nicole

![2020-05-08 11-38-06](https://user-images.githubusercontent.com/3033160/81393626-fa260c80-9120-11ea-8328-945398cc0c81.png)

**Comment by coastforge-fsc** [comment]
Hi Nicole,
das Problem ist gelöst. Ist so allerdings noch nicht im JS-Build. Das würde dann mit einer Version morgen kommen.
VG
Friedrich

**Comment by coastforge-mei** [comment]
Friedrichs Korrektur ist in der v7.0.20 enthalten. Die Version steht ab sofort zur Verfügung.
