### ISSUE TITLE
Clusterblasen - Position und Darstellung

### ISSUE THREAD

**Issue by BennyK80** [Kuestenschmiede/MapsBundle#39]
Die Position der Clusterblasen ist aktuell immer oben links an der eingegebenen Größe des Icons ausgerichtet. Bei Skalierung des Icons bleibt die Clusterblase unverändert an dieser Position.

Aus meiner Sicht wäre es besser...

a) die Clusterblasen zentrieret am Nullpunkt der Location auszurichten und die Icons dann auszublenden.

oder

b) die Clusterblasen individuell zu positionieren, so dass sie sich exakt über dem Icon befinden.

Über eine Anpassung würde ich mich freuen.

**Comment by coastforge-fsc** [comment]
https://github.com/Kuestenschmiede/MapsBundle/commit/874b2b08b11a7938f08e5b3d45d5e80a43ed0a8a
Ich glaube damit habe ich Option b gewählt.
Die Blasen werden jetzt sowohl von der Ausrichtung als auch von der Größe genauso skaliert, wie das Icon
