### ISSUE TITLE
Tooltips - Positionierung / Darstellung

### ISSUE THREAD

**Issue by BennyK80** [Kuestenschmiede/MapsBundle#40]
1.
Wie kann die Position der Tooltips beeinflusst werden?
Aktuell stehen sie immer rechts von der Location.

2.
Wie kann die Darstellung der Tooltips beeinflusst werden?
Schriftart, Schriftgröße, Schriftfarbe, Hintergrundfarbe, Schatten, Eckradius

**Comment by coastforge-fsc** [comment]
Die Orientierung des Tooltips (relativ zum Mauszeiger) lässt sich jetzt im Profil einstellen. https://github.com/Kuestenschmiede/MapsBundle/commit/50dd3571072aaf253bd0f45141d31706dcc7387e
Die Darstellung des Tooltips wird auch mit über das Kartenlayout gesteuert.
Wenn du es allerdings seperat stylen willst, kannst du die Klasse "c4g-tooltip-popup" benutzen.
