### ISSUE TITLE
Marker - Z-Sortierung

### ISSUE THREAD

**Issue by BennyK80** [Kuestenschmiede/MapsBundle#41]
Marker, die auf der Y-Achse oben stehen, sollten optisch hinter den Marken stehen, die auf der Y-Achse weiter unten stehen.

**Comment by coastforge-fsc** [comment]
Hallo Benny,
du meinst jetzt dabei, wie Kartenstrukturelemente mit ihren zIndizes in der Karte dargestellt werden?
Was meinst du in diesem Zusammenhang mit der Y-Achse?

**Comment by BennyK80** [comment]
Ja, genau.
Mit Y-Achse meine ich die Reihenfolge von oben nach unten (Nord-Süd).
Aktuell überlappen nördliche Kartenstrukturelemente die südlichen Kartenstrukturelemente.

**Comment by coastforge-fsc** [comment]
An sich ist das ein guter Ansatz. Allerdings nutzen wir den zIndex bereits um Punkte über Polygonen darzustellen. Einen zIndex an einem Element (,was hier nötig ist,) kann man lediglich über den Style setzen. Damit ist leider kein Vergleich zwischen Elementen möglich. In der StyleFunction könnte man die  90-Y-Koordinate (Gradkoordinaten) als zIndex setzen. Ich werde das mal ausprobieren

**Comment by BennyK80** [comment]
Ich weiß nicht genau, wie es progammiertechnisch funktioniert. 
Aber vielleicht reicht es ja schon, die Daten (den Array?) nach Y-Wert zu sortieren.

**Comment by coastforge-fsc** [comment]
![zIndex_Elements](https://user-images.githubusercontent.com/25226016/84477679-4cae9780-ac90-11ea-94eb-789449283302.png)
Ich habe jetzt einen Ansatz. Passt es so wie im Bild für dich?

**Comment by BennyK80** [comment]
Perfekt! Danke!

**Comment by coastforge-fsc** [comment]
Ok. Dann commite ich das und eine Version kommt, wenn ich die restlichen Issues bearbeitet habe
