### ISSUE TITLE
Tab-Fokus halbiert Karte

### ISSUE THREAD

**Issue by alce221b** [Kuestenschmiede/MapsBundle#45]
Beim Durchgehen der Karte mit der Tab-Taste erscheint nach dem Attribution-Icon eine leere Sidebar, bei der der Schließen-Button nicht reagiert. 
![con4gis_map_fehlt](https://user-images.githubusercontent.com/73824632/97858335-4a141380-1cff-11eb-80fc-c35e5a74930d.PNG)  

Beim weiteren Drücken der Tab-Taste ist die Karte halbiert. 
![con4gis_map_halb](https://user-images.githubusercontent.com/73824632/97858680-cc043c80-1cff-11eb-8c0a-9994edff3559.PNG)
Dieser Zustand bleibt bis zum Neuladen der Seite oder bis das Sideboard geöffnet wird. 

Es wird Contao 4.4 und die Map in der Version 7.2.1 verwendet.

**Comment by coastforge-fsc** [comment]
Mit dem Commit da6d68ddc4b6c041e146ab3c18ed1b15709df1c9 gefixed. Bis zu einer Version kann das mit der folgenden CSS-Anweisung repariert werden.

.c4g-sideboard.c4g-close {
  visibility: hidden;
}
