### ISSUE TITLE
PopUp öffnen nach Suche, JS Fehler

### ISSUE THREAD

**Issue by Misco** [Kuestenschmiede/MapsBundle#46]
Hallo

Wenn ich die Funktion nutzen möchte gibt es einen js Fehler und das Popup bleibt geschlossen:

Uncaught TypeError: Cannot read property 'html' of undefined at Object.<anonymous> (c4g-maps.js?v=1605123134:304)
if(**window.c4gMapsPopup.$content.html**(""),window.c4gMapsPopup.popup.addClass(c.cssConstants.ACTIVE).addCl...

woran kann dies liegen? Danke

**Comment by coastforge-mei** [comment]
Hi Misco,

tritt der Fehler aktuell noch auf? Aufgrund der Meldung können wir leider nicht wirklich eine Aussage treffen. Scheinbar hat Dein Popup keinen Inhalt gehabt. Das Popup kann über eigene Daten, über die Kartenstruktur oder auch über die Lokationsstile gefüllt werden. Ich gehe davon aus, dass das ein Konfigurationsfehler war. Dennoch werde ich mir den Sourcecode gleich noch mal anschauen und den Fehler mit der nächsten Version abfangen. Sorry, dass ich mich erst jetzt melde.

**Comment by coastforge-mei** [comment]
Der Fehler sollte mit der 7.2.5 nicht mehr auftreten.
