### ISSUE TITLE
Konflikt mit Bundle markocupic/calendar-event-booking-bundle?

### ISSUE THREAD

**Issue by planepix** [Kuestenschmiede/MapsBundle#5]
Ahoi an die Küste, hallo Matthias,

ich bekomm einen Konflikt / Fehler im Backend, wenn ich diese Erweiterung neben den coin4gis:maps installieren: https://github.com/markocupic/calendar-event-booking-bundle

Marko hat eine Idee /Ansatz formuliert:
https://github.com/markocupic/calendar-event-booking-bundle/issues/5#issuecomment-366739611

Ist das etwas, das im con4gis_maps Bundle mit berücksichtigt werden muss, damit beide Bundles ohne Konflikte funktionieren?

Danke für eine Einschätzung.
Beste Grüße
Thomas

**Comment by coastforge-mei** [comment]
Moin Thomas,

bei der Installation vom calendar-event-booking-bundle bekomme ich keine Konflikte und bei uns wird in der Plugin.php auch Contao vorausgesetzt (con4gis/core). Im Backend kann ich keinen Fehler feststellen. Muss ich "etwas" parallel zur Karte auf eine Seite bringen um den Fehler nachzustellen?
 Werde mich da die Tage noch mal intensiver mit beschäftigen.

Beste Grüße
Matthias

**Comment by planepix** [comment]
Hallo Matthias,
besten Dank für deine Antwort.

Der Fehler entsteht im Backend, wenn ich bei einem Event das Anmeldeformular einbinden möchte und dort die Option „Buchungsoptionen öffnen” aktiviere und dann das Event speichern möchte.

Nur wenn es deine Zeit erlaubt danach schauen - ich kann dir wieder den Zugang zur Testumgebung geben, dann geht das vermutlich schneller, ohne alle Elemente und Konfigurationen anzulegen.

Danke und Grüße nach Jever
Thomas

**Comment by coastforge-mei** [comment]
Hallo Thomas,
ich kann mir vorstellen, dass der Fehler durch das mehrfache "Zusammenmergen" der DCA Palette auftritt.  Ich habe dazu bereits kleinere Änderungen gemacht. Wir werden aller Voraussicht nach noch in dieser Woche neue Versionen erstellen. Sollte der Fehler danach immer noch auftreten, dann schick mir bitte den Backend-Zugang.
LG
Matthias

**Comment by coastforge-mei** [comment]
Neue Versionen sind verfügbar. Bitte mal testen. Falls der Fehler weiterhin auftritt, gibt mir bitte den Zugang zur Testumgebung.

Schönes Wochenende
Matthias

**Comment by planepix** [comment]
Moin Matthias,
eben die letzte aktualisierte Version installiert. Kein Konflikt mehr mit tl_calendars_events. Dann die Erweiterung von Marko noch dazu installiert. Auch hier kein Fehler mehr im Backend. Danke dir!
