### ISSUE TITLE
Backend - DebugMode und Systemwartung - Warning: Invalid argument supplied for foreach()  

### ISSUE THREAD

**Issue by berecont** [Kuestenschmiede/MapsBundle#53]
Contao 4.9.14  
con4gis Version v7.3.2  

Backend bringt im DebugMode Fehlermeldung, wenn ich in die "Systemwartung" möchte:  
Warning: Invalid argument supplied for foreach()  
in C:\laragon\www\myDomain\vendor\contao\core-bundle\src\Resources\contao\classes\PurgeData.php (line 104)   

`
                    'group' => 'folders',
                    'affected' => ''
                );
                // Get the current folder size
                foreach ($config['affected'] as $folder)
                {
                    $total = 0;
                    $folder = sprintf($folder, $strCachePath);
                    // Only check existing folders`
DebugMode ausgeschalten: Systemwartung ist möglich  
Andere Seiten des Backends dürften nicht betroffen sein.

[Link zum Forum-Thread](https://community.contao.org/de/showthread.php?81003-Backend-Debug-Mode-Warning-Invalid-argument-supplied-for-foreach()&p=544971&viewfull=1#post544971)

**Comment by coastforge-cro** [comment]
Das ist ein Fehler aus dem con4gis/core. Diesen haben wir jetzt gefixt. Das wird mit der nächsten Version behoben. Alternativ kannst du dir die Änderung [hier](https://github.com/Kuestenschmiede/CoreBundle/commit/7a131c69530935ea5252ef9d1988346ef6c00e4e) ansehen und manuell nachziehen, dann hättest du es direkt drin.

**Comment by coastforge-mei** [comment]
Die Änderung ist in con4gis/core 5.0.1 enthalten.
