### ISSUE TITLE
Backend - DebugMode und Con4gis » Dashboard » Einstellungen - Warning: htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by berecont** [Kuestenschmiede/MapsBundle#54]
Contao 4.9.14
con4gis Version v7.3.2
inkl. [Änderung aus Issue #53](https://github.com/Kuestenschmiede/CoreBundle/commit/7a131c69530935ea5252ef9d1988346ef6c00e4e)  

Backend bringt im DebugMode Fehlermeldung, wenn ich im Con4gis Dashboard die Einstellungen aufrufe:  
Warning: htmlspecialchars() expects parameter 1 to be string, array given  
`{
            $strString = static::stripInsertTags($strString);
        }
        // Use ENT_COMPAT here (see #4889)
        return htmlspecialchars($strString, ENT_COMPAT, Config::get('characterSet'), $blnDoubleEncode);
    }
    /**
     * Remove Contao insert tags from a string
     *`  
DebugMode ausgeschalten: Einstellungen aufrufen ist möglich

**Comment by coastforge-mei** [comment]
Tritt der Fehler auch in der aktuellen v8.0.4 auf? Wenn Du den Editor nicht nutzt, dann ist ein Update problemlos möglich. Ich teste aber gleich mal, ob der Fehler bei mir auch auftritt.

**Comment by coastforge-mei** [comment]
Es treten Fehler und Warnungen im Debug auf. Sorry. Neue Version kommt noch heute.

**Comment by berecont** [comment]
Prima! Hatte soeben ein Update via CM auf 8.0.4 gemacht.
Im Backend wird mir trotzdem noch die 7.3.2 angezeigt.
![2021-05-31 11_54_54-Dashboard _ lupus](https://user-images.githubusercontent.com/33038265/120176533-aee90b00-c207-11eb-9039-24b7f036ff57.jpg)

**Comment by coastforge-mei** [comment]
Danke für die Info. Wir holen nicht jedes Mal die Versionen ab. Das ist schon etwas zeitintensiv. Deshalb gibt es oben den Button "Versionen aktualisieren". Aktuell ist es so, dass spätestens nach sieben Tagen immer ein Update der Versionen gemacht wird. Ansonsten wird geprüft ob Pakete dazu gekommen sind oder ähnlich. Da lässt sich aber auf jeden Fall noch was machen. Ich überlege mir was.

**Comment by coastforge-mei** [comment]
Die debug warnings sind behoben (core 5.0.3 + maps 8.0.5).
