### ISSUE TITLE
Con4Gis-Maps 8.06, - Contao 4.11.3

### ISSUE THREAD

**Issue by soweit-ok** [Kuestenschmiede/MapsBundle#55]
**input type="text" id="c4g-geosearch-input"** (Lupe-Button)
Nach Submit wird zwar die Suche gestartet und die Karte führt den Zoom in den Bereich aus, der Gesamtvorgang, jedoch nicht abgeschlossen. Im Starboard werden keine Suchergebnisse mehr angezeigt und auch alles andere verschwindet - nur der komplett leere Starboard-Hintergrund bleibt noch davon übrig.  Hernach ist die Seite tot und erst nach Reload wieder benutzbar. 
In der Konsole wird ein React-Fehler ausgegeben: 

`Uncaught Error: Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Bu https://kartenseite.de/bundles/con4gismaps/build/c4g-maps.js:2
    Ei https://kartenseite/bundles/con4gismaps/build/c4g-maps.js:2
    ........
....../bundles/con4gismaps/build/c4g-maps.js
**c4g-maps.js:2:113916`**
---------------
Wohl weil 2stufig gezoomt wird, wird die Meldung in der Konsole 2x geworfen, 

Dieses Update war ne ziemliche Zitterpartie. Zunächst lief das Composer-Update mit Dependencies erst garnicht durch, wg. des Doctrine-Bugs. Erst nach Entfernen problematischer Con4Gis-Bundles. Anschließend funktionierte dennoch keinerlei Updates und es knallte richtig  bei Versuchen - Install-Tool, BE und FE nicht mehr erreichbar. Erst nach kompletter De- und Neuinstallation sämtlicher installierter Con4Gis-Bundles klappte das schließlich. 
Bis auf vor dem Update nicht vorhandene neue Bugs:
Anscheinend wird das Template mod_c4g_brick_list.html5 nicht mehr ausgeführt. Damit auch nicht der darin ergänzte Code und auch Dump der Template-Variablen nicht. Vielleicht kein Fehler und soll so sein? Falls ja, hatten wir schonmal, nach euren Template-Änderungen in Maps 7 und könntet Anwender erfreuen, sowas künftig zu posten. :-)

Sonst scheint alles nun wieder zu laufen, soweit ich es bis jetzt nach ziemlich gründlichen Test sagen kann. Mehr konnte ich nicht zu diesem Fehler rausfinden.

**Comment by coastforge-mei** [comment]
Den Fehler kann ich nachstellen. Wir werden uns da morgen drum kümmern. 

Zur Info: Die Templates _brick_list und _brick_simple gibt es mit con4gis 8 nicht mehr. Wir haben beide Varianten im neuen Template mod_c4g_brick.html5 vereint.

**Comment by soweit-ok** [comment]
Oh, auch noch zu so sportlicher Uhrzeit zugange. Danke für das rasche Feedback! Ah ja, demnach tatsächlich damit zusammenhängende Folgefehler. 
Allein eigener Templatecode war kein großartiges Problem. Der ließ sich ja auch anderenorts platzieren, nachdem ich erstmal raus hatte, dass dies ganze Template  nicht mehr ausgeführt wird.

**Comment by coastforge-mei** [comment]
Ist mit der 8.0.7 behoben. Danke für die Meldung.

**Comment by soweit-ok** [comment]
Ebenso danke für die schnelle Behebung

**Comment by soweit-ok** [comment]
Funktioniert wieder wie es soll. Eine andere positive Beobachtung - mal schauen ob der Trend beständig bleibt, auffällige Performance-Verbesserung einer komplexen Kartenseite.  Falls nicht bloß vorrübergehende Zufallsausreißer, womöglich infolge von Beiseitigung einiger Altlasten? Rhetorische Frage .... wird sich ja zeigen.
Jetzt jedenfalls bei ca. 30 Seitenaufruftests durchgängig domready ca. 650ms und onload ca. 1.0s. Bislang waren die besten Messwerte in der verwendeten Testumgebung trotz diverser Optimierungsmaßnahmen nie unter 950ms/1.8s zu bringen (Messung mit ADSL-Speeddrossel). Hinzu kommt noch ein Haufen individueller Zusatzprogramme auf dem Client, was Seitenbesuchern insg. weitere ca. 200ms Geduld bis zur vollständigen Verfügbarkeit abverlangt, 
Hut ab! Funktional kam während des v7.x-Zyklus nicht mehr allzuviel hinzu. Dennoch fiel ja auf, dass ihr derweil "unter der Haube" unerlässlich heftig am Wirbeln wart.  War den den "Angstschweiß" bei der Durchführung dieses Updates auf v8 gewiss wert. ;-)
