### ISSUE TITLE
Contao-Konfig berücksichtigen

### ISSUE THREAD

**Issue by katgirl** [Kuestenschmiede/MapsBundle#57]
Die Contao-Konfig für den Suffix sollte berücksichtigt werden:
https://github.com/Kuestenschmiede/MapsBundle/blob/c383abeeceedf928a14af0e47365cd1a417ec2fd/Resources/contao/modules/api/LayerContentDataApi.php#L182-L185

**Comment by coastforge-mei** [comment]
Du hast Recht. Danke für den Hinweis. Wir werden das anpassen.

**Comment by katgirl** [comment]
Das scheint aber in der Klasse noch an weiteren Stellen notwendig zu sein ;-)

**Comment by coastforge-cro** [comment]
Wird in der nächsten Version angepasst.
