### ISSUE TITLE
Direktverlinkung geht bei Datenbezug nicht

### ISSUE THREAD

**Issue by katgirl** [Kuestenschmiede/MapsBundle#58]
Wenn ich eine externe Tabelle zum Datenbezug nehme wird immer ein PopUp aufgemacht. Eine Direktverlinkung ist nicht möglich.

![image](https://user-images.githubusercontent.com/1223243/122359121-93933500-cf55-11eb-92bc-9db83296aef2.png)
![image](https://user-images.githubusercontent.com/1223243/122359271-b4f42100-cf55-11eb-8d9a-33bb9fc1ce83.png)
![image](https://user-images.githubusercontent.com/1223243/122359589-f84e8f80-cf55-11eb-93f7-14a6d53e3519.png)

**Comment by coastforge-cro** [comment]
Das wurde in https://github.com/Kuestenschmiede/MapsBundle/commit/82328f0ada021816255696c4af75f2907987c63e behoben und wird mit in die nächste Version kommen. In dem Zusammenhang wurde auch die Contao-Konfig für das URL-Suffix berücksichtig (siehe https://github.com/Kuestenschmiede/MapsBundle/issues/57).

**Comment by coastforge-mei** [comment]
Gerne mal in der 8.0.9 testen.

**Comment by katgirl** [comment]
Danke funktioniert super, habe euch gestern auch noch ne Anfrage geschickt.

**Comment by coastforge-mei** [comment]
Auf welchem Kanal hast Du Deine Anfrage geschickt? Bei mir ist bisher nichts angekommen. Schick das ansonsten gerne noch mal per E-Mail.

**Comment by katgirl** [comment]
per E-Mail an ahoi@kuestenschmiede.de

**Comment by coastforge-mei** [comment]
Ja, gerne noch mal. Bisher ist leider nichts durchgekommen.
