### ISSUE TITLE
Keine Touch-Navigation auf iPad (iOS 12.5.4)

### ISSUE THREAD

**Issue by lebleucleu** [Kuestenschmiede/MapsBundle#59]
Zuerst einmal herzlichen Dank für die tolle Erweiterung!
Bei der Umsetzung einer Anfahrtskarte bemerkte ich, dass die Touch-Navigation auf dem iPad nicht möglich ist. Dies betrifft alle getesteten Browser (Safari, Chrome, Firefox). Vgl. z.B. https://maps.con4gis.org/anreisekarte
Bei einer Karte mit Globusdarstellung (Cesium) funktioniert die Touch-Navigation.

**Comment by coastforge-fsc** [comment]
Das ist ein Problem mit fehlenden Polyfills bei älteren iOS-Geräten. Das ist mit [diesem Commit](https://github.com/Kuestenschmiede/MapsBundle/commit/fd4887fbc0d65e976b02c5fc191448814c45013e)  behoben. Falls das Problem live bei dir auftritt, kannst du die Polyfills auch so '<script src="https://unpkg.com/elm-pep"></script>' laden.

**Comment by lebleucleu** [comment]
'<script src="https://unpkg.com/elm-pep"></script>' funktioniert auf Anhieb.
Danke für die schnelle Lösung!
