### ISSUE TITLE
Unter Contao 4.12.1 nicht installationsfähig

### ISSUE THREAD

**Issue by dp-designpilot** [Kuestenschmiede/MapsBundle#61]
Hallo

Was kann ich da machen, muss ich da in der **composer.json** noch was machen ??

Ich habe die Versionen **8.0.0** - **8.0.21** getestet, aber jedes mal praktisch die gleiche Meldung. Die einzige Version die beim Testlauf ohne Fehler durchläuft ist die Version **7.3.2**

> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!
[6.9MiB/0.18s] Loading composer repositories with package information
[63.0MiB/1.84s] Updating dependencies
[1478.0MiB/18.17s] Your requirements could not be resolved to an installable set of packages.
[1478.0MiB/18.17s] 
  Problem 1
    - Root composer.json requires con4gis/maps ^8.0 -> satisfiable by con4gis/maps[v8.0.0, ..., v8.0.21].
    - Conclusion: don't install symfony/framework-bundle v5.3.4 (conflict analysis result)
    - contao/manager-bundle 4.12.1 requires symfony/web-profiler-bundle ^4.4 || ^5.2 -> satisfiable by symfony/web-profiler-bundle[v5.3.5].
    - contao/manager-bundle is locked to version 4.12.1 and an update of this package was not requested.
    - symfony/web-profiler-bundle v5.3.5 requires symfony/framework-bundle ^5.3 -> satisfiable by symfony/framework-bundle[v5.3.0, v5.3.2, v5.3.3, v5.3.4].
    - symfony/framework-bundle v5.3.3 conflicts with symfony/framework-bundle v5.3.3.
    - symfony/framework-bundle v5.3.2 conflicts with symfony/framework-bundle v5.3.2.
    - symfony/framework-bundle v5.3.0 conflicts with symfony/framework-bundle v5.3.0.
    - Conclusion: install symfony/console v4.4.29 (conflict analysis result)
[1478.0MiB/18.17s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[77.4MiB/19.63s] Memory usage: 77.44MB (peak: 1481.03MB), time: 19.64s.
[77.4MiB/19.63s] Finished Composer Cloud resolving.

Freundliche Grüsse

**Comment by coastforge-mei** [comment]
Moin Designpilot,

da der Kollege meines Wissens da noch dran ist. Nur die kurze Nachfrage: wie wurde das Problem gelöst?

Beste Grüße

**Comment by dp-designpilot** [comment]
Hallo coastforge-mei
Ich habe einfach bei der 4.12.1 alle Pakete zum Update markiert, dann die Erweiterung zum Update markiert und danach die con4gis-Reservation Erweiterung installiert dann hat es funktioniert.
