### ISSUE TITLE
Global scope von img styles

### ISSUE THREAD

**Issue by typo3rel** [Kuestenschmiede/MapsBundle#62]
Hallo,
erstmal ein Danke für die tolle Arbeit.
Eine Sache ist mit aber aufgefallen: Meine Icons auf der Seite mit der Map sind riesig :)
Ich denke das Problem ist in der _c4g-maps-general.scss ab Zeile 1465:  img "width: 100%;" und .btn im Global Scope

Version 8.0.25

Danke fürs Fixen ;)

**Comment by katgirl** [comment]
hat mir auch gerade mehrere Seiten zerschossen

**Comment by coastforge-mei** [comment]
Wir sind dran. Danke für die Meldung.

**Comment by coastforge-mei** [comment]
Der Fehler wurde mit der Version 8.0.26 behoben.
