### ISSUE TITLE
Issues with Contao 4.12.1 - Symfony 4 and 5 incompatibilities

### ISSUE THREAD

**Issue by hwit-biz** [Kuestenschmiede/MapsBundle#65]
Good morning,

yesterday I tried to install a brand new Contao 4.12.1 project with the MapsBundle. There are actually some errors which stop the desired Frontend pages from being display at all. Only the Contao page "Something went wrong" appears. At least I think I could fix the first two issues with Pull Request #64 - however, I will explain the three issues with the following posts.

**Comment by hwit-biz** [comment]
The first issue appeared with the EventDispatcher:

> [2021-09-22T21:30:52.994791+01:00] request.INFO: Matched route "tl_page.7". {"route":"tl_page.7","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.7","_route_object":{"Contao\\CoreBundle\\Routing\\Page\\PageRoute":[]}},"request_uri":"https://xxx.xx/kontakt.html","method":"GET"} []
> [2021-09-22T22:30:53.064087+02:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
> [2021-09-22T21:31:21.613108+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Event" from namespace "Symfony\Component\EventDispatcher". Did you forget a "use" statement for e.g. "Symfony\Contracts\EventDispatcher\Event", "Spatie\SchemaOrg\Event", "Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Event" or "FOS\HttpCache\Event"?" at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/con4gis/maps/Classes/Events/LoadProfileEvent.php line 15 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Event\" from namespace \"Symfony\\Component\\EventDispatcher\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Contracts\\EventDispatcher\\Event\", \"Spatie\\SchemaOrg\\Event\", \"Nelmio\\SecurityBundle\\ContentSecurityPolicy\\Violation\\Event\" or \"FOS\\HttpCache\\Event\"? at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/con4gis/maps/Classes/Events/LoadProfileEvent.php:15)"} []

This should be related to this news: https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

A possible fix is included in Pull Request #64 - please check for compatibility.

**Comment by hwit-biz** [comment]
The second issue appeared with the service controllers:

> [2021-09-22T22:15:35.530921+01:00] request.INFO: Matched route "layer_service". {"route":"layer_service","route_parameters":{"_route":"layer_service","_controller":"con4gis\\MapsBundle\\Controller\\LayerController::layerAction","mapId":"1","lang":"de"},"request_uri":"https://xxx.xx/con4gis/layerService/1/de","method":"GET"} []
> [2021-09-22T22:15:35.743571+01:00] request.CRITICAL: Uncaught PHP Exception LogicException: ""con4gis\MapsBundle\Controller\LayerController" has no container set, did you forget to define it as a service subscriber?" at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 36 {"exception":"[object] (LogicException(code: 0): \"con4gis\\MapsBundle\\Controller\\LayerController\" has no container set, did you forget to define it as a service subscriber? at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:36)"} []
> [2021-09-22T22:15:35.637682+01:00] request.INFO: Matched route "baselayer_service". {"route":"baselayer_service","route_parameters":{"_route":"baselayer_service","_controller":"con4gis\\MapsBundle\\Controller\\BaselayerController::baseLayerAction","profileId":"2","lang":"de"},"request_uri":"https://xxx.xx/con4gis/baseLayerService/2/de","method":"GET"} []
> [2021-09-22T22:15:35.827015+01:00] request.CRITICAL: Uncaught PHP Exception LogicException: ""con4gis\MapsBundle\Controller\BaselayerController" has no container set, did you forget to define it as a service subscriber?" at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 36 {"exception":"[object] (LogicException(code: 0): \"con4gis\\MapsBundle\\Controller\\BaselayerController\" has no container set, did you forget to define it as a service subscriber? at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:36)"} []

This should be related to this change: https://github.com/symfony/dependency-injection/blob/4.0/CHANGELOG.md

So I digged into possible fixes and came up with the parameter `autowire: true` for the service containers. This is also probably fixed in Pull Request #64 - but I'm not sure if it doesn't break other things because...

**Comment by hwit-biz** [comment]
... there is another issue where I had to stop because I have no clue where to even start with:

[2021-09-23T00:09:29.381825+01:00] request.INFO: Matched route "locationstyle_service". {"route":"locationstyle_service","route_parameters":{"_route":"locationstyle_service","_scope":"frontend","_controller":"con4gisMapsBundle:Locationstyle:locationStyle"},"request_uri":"https://xxx.xx/con4gis/locationStyleService/?ids%5B0%5D=1","method":"GET"} []
[2021-09-23T00:09:29.489682+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-09-23T00:09:29.505126+01:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/con4gis/locationStyleService/" is not callable: Controller "con4gisMapsBundle:Locationstyle:locationStyle" does neither exist as service nor as class." at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/con4gis/locationStyleService/\" is not callable: Controller \"con4gisMapsBundle:Locationstyle:locationStyle\" does neither exist as service nor as class. at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"con4gisMapsBundle:Locationstyle:locationStyle\" does neither exist as service nor as class. at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:67)\n[previous exception] [object] (Error(code: 0): Class 'con4gisMapsBundle:Locationstyle:locationStyle' not found at /mnt/web412/b3/58/59718458/htdocs/contao/vendor/symfony/http-kernel/Controller/ControllerResolver.php:147)"} []

Maybe someone else has a clue, but I'm out. I simply have no idea why this service container is not recognized along all others.

Would be very thankful if someone could take a look at this issues and also fix any further compatibility issues with newer Symfony versions on Contao 4.12.1.

**Comment by hwit-biz** [comment]
Hey there,

last issue is related to Update 5.0 of Symfony:

> Removed support for bundle:controller:action syntax to reference controllers. Use serviceOrFqcn::method instead where serviceOrFqcn is either the service ID when using controllers as services or the FQCN of the controller.
> 
> Before:
> 
> bundle_controller:
>     path: /
>     defaults:
>         _controller: FrameworkBundle:Redirect:redirect
> After:
> 
> bundle_controller:
>     path: /
>     defaults:
>         _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction

In the meantime @coastforge-cro has fixed the problem with commit 6fc983662521ed7f036d47c8e795f3fd57ae8ac3 (alongside with other optimizations for Symfony 5).

Thank you very much!

PS: Maybe this issue could be helpful also for Kuestenschmiede/CoreBundle etc.?

**Comment by coastforge-cro** [comment]
First of all, thank you for your debugging efforts and your PR. I've merged that one, I guess you've already seen that.

We are currently investigating which of our other bundles need adjustments for Symfony 5. We will issue new releases of the affected bundles as soon as we have modified these bundles, if needed.

**Comment by hwit-biz** [comment]
Thanks for your efforts, I've seen the PR merged. As this was my first PR with a separate fork I think things went good all along. Meanwhile I removed my fork and my branch so everything is clean again. However I have cloned the repos for MapsBundle and CoreBundle because those are the ones I'm currently using. Maybe I can help on future revisions as well.

Greetings, Harry.
