### ISSUE TITLE
Modul "Quelltabellen" im Backend nicht mehr aufrufbar (Contao 4.12.3 / con4gis-Maps 8.0.35)

### ISSUE THREAD

**Issue by soweit-ok** [Kuestenschmiede/MapsBundle#67]
Moin moin,
könntet Ihr das bitte mal prüfen? Vielen Dank!
**Fehlermeldung:**
`Argument 1 passed to Contao\CoreBundle\Util\LocaleUtil::formatAsLocale() must be of the type string, null given, called in /.../projekte/ecom/vendor/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php on line 1375`
**Symfony  Stack Trace:**
TypeError
in vendor/contao/core-bundle/src/Util/LocaleUtil.php (line 108)
in vendor/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php :: formatAsLocale (line 1375)
in vendor/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php -> languageMatches (line 631)
in vendor/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php -> doReplace (line 58)
in vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php -> replace (line 805)
**in vendor/con4gis/maps/Resources/contao/dca/tl_c4g_map_tables.php :: replaceInsertTags (line 402)**
in vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php -> addIcon (line 5030)
in vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php -> listView (line 350)
in vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php -> showAll (line 648)
in vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php -> getBackendModule (line 167)
in vendor/contao/core-bundle/src/Controller/BackendController.php -> run (line 49)
in vendor/symfony/http-kernel/HttpKernel.php -> mainAction (line 158)
in vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 80)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 201)
Kernel->handle(object(Request)) in web/index.php (line 31) 
--------------
Ob der Fehler erst mit Update zu Cto. 4.12.3 auftrat, kann ich nicht sagen, weil ich einen BE-Aufruf von "Quelltabellen"  seit längerer Zeit nicht mehr testete - bisher keine eig. Quelltabellen hinzugefügt. Ein Downgrade zu Cto. 4.12.2 brachte jedenfalls keinen Erfolg, gleiche Exeption. Wenn auch nicht ganz dasselbe ... ein ähnlicher Bug wurde vor ca. 2 Wochen auch in Verbindung mit Isotope 2.7 gemeldet nach Update Cto. 4.12.2 > 4.12.3. Siehe [https://github.com/contao/contao/issues/3593](url)
LG Andreas

**Comment by soweit-ok** [comment]
**Nachtrag:**
Zwischenzeitlich änderte ich testhalber mal in vendor/con4gis/maps/Resources/contao/dca/tl_c4g_map_tables.php bei der Funktion "addIcon" Zeile 402 zu
`$args[1] = /*\Contao\Controller::replaceInsertTags($args[1]);*/'';`
... so dass also statt des fehlschlagenden replaceInsertTags einfach ein Leerstring zurückgegeben wird.
Anschließend im CM den Prod.-Cache erneuert und das Quelltabellen-Modul im BE erneut aufgerufen. Funktionierte nun wieder und erschien auch keine Fehlermeldung mehr. Erwartungsgemäß wurden in der Liste natürlich in der Spalte "Name" keine Label-Einträge mehr angezeigt. Im Bearbeitungsformular der Tabellen inkl. der eingetragenen Feldwerte alles korrekt identisch mit einer älteren nicht mehr weitergepflegten Installation (Cto. 4.9.14 / con4gis-Maps 7.3.2).
Immerhin ist damit klar, wo es herkommt und es sonst wie bisher funktioniert. Vermutlich wurde etwas im Contao-Kern verändert, dass es so nicht mehr klappt. Recherche förderte mehrere Issues zum zugrundeliegenden Problem zutage bzw. auch andere Bundles als con4gis-Maps betreffend,

**Comment by coastforge-mei** [comment]
HI Andreas,
habe die Übersetzung an der Stelle einfach ausgebaut (8.0.36). Dank Dir für die Info. Der Fehler trat bei mir in der 4.12 auch auf.

**Comment by soweit-ok** [comment]
Hallo Matthias,
vielen Dank. Ja klar, hier keine Übersetzung erforderlich. Zumal "Name" kein Pflichtfeld und die Listenanzeige der referenzierten Quelltabellen eigentlich schon reicht.
