### ISSUE TITLE
Missing PHP requirement

### ISSUE THREAD

**Issue by fritzmg** [Kuestenschmiede/MapsBundle#68]
All version 8.x tags currently do not define their PHP requirement. This makes this package installable in PHP 8 for instance - however the extension does not seem to be compatible with PHP 8 yet. It also makes the package installable in PHP versions that are below the package's minimum requirements.

Is there a specific reason why you removed the PHP requirement in 80ea0fd626bcbd638cf683d9958cc67113e60129 ?

**Comment by coastforge-fsc** [comment]
The PHP requirement is also in the composer.json of the [CoreBundle](https://github.com/Kuestenschmiede/CoreBundle/blob/main/composer.json). Is there a reason to have the requirement in both?
We are still fixing some bugs, but the bundle should be compatible with PHP 8. Could you elaborate which parts are not compatible, so we can fix them?

**Comment by fritzmg** [comment]
It's best practise to define the PHP requirements in each package so that everyone working on each package independently knows what to support or expect.

One PHP 8 error was reported here: https://community.contao.org/de/showthread.php?82404-Con4gis-Maps-Fehler-php8-0

**Comment by coastforge-mei** [comment]
Thank you for your input. We are now adding the php version to each bundle as additional information for the packagist.
