### ISSUE TITLE
Fehler 404 im Backend, Logo-Bild nicht gefunden (Version 5.0.3)

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#7]
Moin,

bei Version 5.0.0 wurde im Backend unter Artikel bei den Inhaltselementen beim Inhaltselement "Karte (con4gis)" ein con4gis Logo mit angezeigt. Bei der Version 5.0.3 wird das Bild nicht gefunden.

Die URL https://example.com/bundles/con4gismaps/images/logo_con4gis-maps.png liefert jetzt Error 404 not found.

Jörn

**Comment by coastforge-mei** [comment]
Oops, da haben wir wohl beim Aufräumen zuviel gelöscht. Mit der 5.0.4 wird es wieder da sein (voraussichtlich noch heute).
