### ISSUE TITLE
Fehler 500 im Backend, Table 'Datenbankname.tl_tag' does not exist

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#8]
Wenn man bei einem Kartenstrukturelement unter Lokation, Typ des Kartenelements (Lokationstyp) die Auswahl "Aus anderer Tabelle" vornimmt, gibt es unter "Quelltabelle" vier Einträge: "Events", "Events mit Tags", "Inhaltselemente", "Mitglieder". Bei Auswahl von "Events mit Tags" erhalte ich den Fehler 500:
`"An exception occurred while executing 'SELECT id, tag FROM tl_tag WHERE from_table ="tl_calendar_events"': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Datenbankname.tl_tag' doesn't exist"`

Neben con4gis habe ich nur die Erweiterungen Changelanguage sowie BackupDB installiert.

Vermutlich wird hier eine Tags-Erweiterung stillschweigend vorausgesetzt.

Lösungsvorschlag:
Abfragen, ob die Tabelle 'Datenbankname.tl_tag' existiert und ansonsten den Eintrag "Events mit Tags" in der Auswahlliste ausgrauen (deaktivieren).
Ich würde den Auswahlpunkt "Events mit Tags" nicht komplett ausblenden, denn so sieht man als Anwender, daß ggf. mit zusätzlicher Erweiterung weitere Konfigurationsmöglichkeiten bestünden.

Jörn

**Comment by coastforge-fsc** [comment]
Der Fehler ist im Master-branch gelöst. Ich weiß leider nicht ganz genau wann die neue Version kommt.
Da die Options für das Feld durch einen options_callback von Contao gesetzt werden, ist ein Ausgrauen leider nicht so einfach möglich.
Friedrich
