### ISSUE TITLE
Warning in debug mode: Attempt to read property "buttonradius" on null

### ISSUE THREAD

**Issue by christianbarkowsky** [Kuestenschmiede/MapsBundle#80]
PHP 8.1
Contao 4.13.x

<img width="1056" alt="Bildschirmfoto 2023-03-29 um 14 05 56" src="https://user-images.githubusercontent.com/1230547/228530133-4b15c0b6-f5f7-4e7a-a5dd-20ad6c03d22b.png">

**Comment by coastforge-fsc** [comment]
fixed in 71e1c1a4aadefb6c7edd0ff61546f8089dacd11c
