### ISSUE TITLE
conflict due to mobiledetectlib ^3.74

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#81]
The dependency on the newest version ^3.74 of the [mobiledetectlib](https://packagist.org/packages/mobiledetect/mobiledetectlib) results in a conflict with other packages like [merger2](https://packagist.org/packages/contao-community-alliance/merger2) which are still depending on the previous version ^2.8 of the mobiledetectlib.
This results in the MapsBundle being stuck at version v8.1.39 without being able to upgrade to any v8.2.x version.
A short test with using mobiledetectlib ^2.8 as a requirement seems to work. So maybe the requirement for the mobiledetectlib could be relaxed to `^2.8 || ^3.74`?

**Comment by coastforge-mei** [comment]
Thank you for your message and solution. We have implemented it directly with version 8.2.9.
