### ISSUE TITLE
Map with events shows in popup unwanted text " LayerContentDataApi.php"

### ISSUE THREAD

**Issue by joehi** [Kuestenschmiede/MapsBundle#82]
The popups of the events in a map show an " LayerContentDataApi.php" at the end of the line. This seems to be the case since a few versions already (v8.1.x).

The responsible code is the following:
https://github.com/Kuestenschmiede/MapsBundle/blob/9d57e1d26c120777d6e3d219f60a9a5d9bc391c6/src/Classes/Services/LayerContentDataService.php#L129

Changing this code to `$popupContent .= System::getContainer()->get('contao.insert_tag.parser')->replace($replacedValue);` by removing the `. ' LayerContentDataApi.php'` at the end seems to solve this problem.

**Comment by coastforge-mei** [comment]
Thank you for your message and solution. We have implemented it directly with version 8.2.9.
