### ISSUE TITLE
require  contao/calendar-bundle

### ISSUE THREAD

**Issue by katgirl** [Kuestenschmiede/MapsBundle#93]
You need the ContaoCalendarBundle
https://github.com/Kuestenschmiede/MapsBundle/blob/main/src/ContaoManager/Plugin.php#L15
https://github.com/Kuestenschmiede/MapsBundle/blob/main/src/ContaoManager/Plugin.php#L47

but neither the comoser.json of the MapsBundle nor the CoreBundle contains the reference. This leads to an error.

**Comment by coastforge-mei** [comment]
Done with [v8.2.24](https://github.com/Kuestenschmiede/MapsBundle/releases/tag/v8.2.24)
