### ISSUE TITLE
Contao 5.3: Adaption of custom backend URL

### ISSUE THREAD

**Issue by jankout** [Kuestenschmiede/MapsBundle#95]
Hello, 

fist of all: thank you very much for the great extension I appreciate very much. 

I would like to suggest an improvement. Unfortunately, not all of the settings items recognise the real backend URL. In my case, I have custom backend URL, it means I use `admin` instead of `contao`. But your settings items expect the previous URL `contao`. Could you fix it, please? Otherwise it's impossible to navigate to it and I have to change the path manually every time. 

Thank you very much.

**Comment by coastforge-mei** [comment]
We have implemented the Contao backend route in con4gis core 7.1.2 and maps 9.0.6.
