### ISSUE TITLE
"Output is not set or a callable..." Contao 5.3

### ISSUE THREAD

**Issue by Patric96** [Kuestenschmiede/MapsBundle#96]
I am receiving the following error in a fresh installed contao 5.3:
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "output is not set or not a callable" at Template.php line 180 {"exception":"[object] (InvalidArgumentException(code: 0): output is not set or not a callable at website/vendor/contao/core-bundle/contao/library/Contao/Template.php:180)"} {"request_uri":"https://xyz.de/con4gis/geopickerService/?geoX=&geoY=&rt=4e849cca4a92b783602db1.9Wnn19S0gmKwk9fTnaJhCftqebuOW3CgN7wdZqYkH9k.kDuInL3E0wDH4piYxJUyW48JM-PPHCHNVMp6FpRKboqZG6-upOvkB9j25w","request_method":"GET"}

It happens, whenever an overlay opens (for example when clicking on the pen to edit a map structure element).

**Comment by coastforge-mei** [comment]
This error has been fixed with version 9.0.6.
