### ISSUE TITLE
Update Contao 5.3.12 auf 5.4.0 scheitert

### ISSUE THREAD

**Issue by Wedego** [Kuestenschmiede/MapsBundle#97]
Zuerst einmal ein Dankeschön für die Erweiterung!
Dann mein Problem, beim Updateversuch auf Contao 5.4.0 bekomme ich folgenden Error:
Fatal error: Type of con4gis\MapsBundle\Controller\LayerController::$container must be Psr\Container\ContainerInterface (as in class Symfony\Bundle\FrameworkBundle\Controller\AbstractController) in /var/www/vhosts/do-domain.de/httpdocs/vendor/con4gis/maps/src/Controller/LayerController.php on line 27
PHP Fatal error:  Type of con4gis\MapsBundle\Controller\LayerController::$container must be Psr\Container\ContainerInterface (as in class Symfony\Bundle\FrameworkBundle\Controller\AbstractController) in /var/www/vhosts/do-domain.de/httpdocs/vendor/con4gis/maps/src/Controller/LayerController.php on line 27
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
Wie kann ich weiter verfahren?
Danke und beste Grüße

**Comment by coastforge-mei** [comment]
Bitte teste das Update erneut mit der Version 9.0.6

**Comment by Wedego** [comment]
Dankeschön für die neue Version.
Leider scheitert mein Updateversuch auf Contao 5.4.3 mit folgenden Fehlern:

> Fatal error: Type of con4gis\MapsBundle\Controller\LayerController::$container must be Psr\Container\ContainerInterface (as in class Symfony\Bundle\FrameworkBundle\Controller\AbstractController) in /var/www/vhosts/domain.de/httpdocs/vendor/con4gis/maps/src/Controller/LayerController.php on line 27
PHP Fatal error:  Type of con4gis\MapsBundle\Controller\LayerController::$container must be Psr\Container\ContainerInterface (as in class Symfony\Bundle\FrameworkBundle\Controller\AbstractController) in /var/www/vhosts/domain.de/httpdocs/vendor/con4gis/maps/src/Controller/LayerController.php on line 27
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255

Die neue Version läßt sich problemlos unter Contao 5.3.15 installieren und die Ext. läuft ;)
Was könnte ich selbst noch tun?

**Comment by Wedego** [comment]
Was könnte ich selbst noch tun?

**Comment by coastforge-mei** [comment]
Fixed with version 9.0.8

**Comment by Wedego** [comment]
Dankeschön für das  Update, toller Service!
Update läuft nun.
Super!
